spring:
  application:
    name: crud-computadora

datasource:
  my-connection:
    jdbc-url: jdbc:oracle:thin:@localhost:1521:SID
    username: AVARGAS
    password: Altair3062002
    maximum-pool-size: 10
    pool-name: "crud-pool"
    auto-commit: true